### PR TITLE
remove instrument sensor fields

### LINKED ISSUE #37: is instrument sensor mandatory or optional
cioos metadata schema dosen't mention sensor and the iso standard indicates it's optional I think. in the template is is said to be mandatory [L935](https://github.com/cioos-siooc/metadata-xml/blob/192130b74ae75c466edf74166a649e9998bccba5/metadata_xml/cioos_template.jinja2#L935). Should it be indicated as optional?

### LINKED ISSUE #38: instrument sensor hosted not needed?
as sensor is child of instrument and hosted indicates the instrument the sensor is on, does it make sense to have hosted tag at all? [L968](https://github.com/cioos-siooc/metadata-xml/blob/192130b74ae75c466edf74166a649e9998bccba5/metadata_xml/cioos_template.jinja2#L968). I think not my self.

### PR DESCRIPTION
**Pull request by n-a-t-e**
Removes all references to the instrument sensor fields, eg `instrument_1_sensor_1_id`, as they are no longer in the CIOOS profile

Resolves #37 
Resolves #38

### CODE REVIEW

**Comment by fostermh** [comment]
this seems fine to me in less someone else is populating sensor info. @jeffcullis?

**Comment by jeffcullis** [comment]
I'm not populating sensor information. I think I'm OK with this being removed but weirdly it seems that sensor is present in the working copy of the CIOOS profile sheet, but not present in the V1 sheet.

**Comment by fostermh** [comment]
highly suspicious. Perhaps this needs clarification with the metadata group?

Matthew Foster
Hakai Institute, Calvert Island, BC, Canada / www.hakai.org
Tula Foundation, Quadra Island, BC, Canada / www.tula.org

**Comment by jeffcullis** [comment]
Yeah it's definitely concerning. I'll try to get some clarity on that one.

**Comment by jeffcullis** [comment]
I haven't heard back on this from Reyna but in talking with Odum we think Reyna must have removed some elements as she created the V1 sheets that won't be commonly used. It's not so much that they aren't allowed but that we may not need to support them initially. Anyway for simplicity it's probably fine to take them out here. Consistency with the V1 sheets should probably be the main goal for now.

**Review by jeffcullis — APPROVED** [review]
Thanks Nate, approving since we're aiming for constitency with version 1 of the profile.

**Pull request merged**
