### PR TITLE
Switch to pygeometa/MCF

### PR DESCRIPTION
**Pull request by n-a-t-e**
I modified the Jinja template to use Pygeometa. It uses their MCF format with many changes to support our profile. This is just a draft PR, still todo:
 - add validation, probably using a validation library eg `pykwalify` or `yamale`
 - add documentation for the fields that are allowed in the YAML file. (changes to MCF)

Unfortunately GitHub is not displaying the diff for main template file, main.j2 below. The file was renamed but I was careful to keep history so dunno why it doesnt work, it displays fine in GitKraken

Update: see the diff for the main template, main.j2, here (click "load diff") https://github.com/cioos-siooc/metadata-xml/pull/57/commits/0124604e2ed39d8bf00246fa23292efd07388989#diff-10b89da1ac38a027382a53e231fb9130

### CODE REVIEW

**Comment by jeffcullis** [comment]
This looks good, thanks Nate. I think we're pretty close to moving forward on merging this in to master. However Jacob was just having some trouble harvesting a file from this branch, and the same issue occurs on the default sample record.

> just to confirm, using the stock record.yml to record.xml, it also has the same harvest error:
Validation Error: {u'Metadata-point-of-contact': u'Missing value at required subfield Name'}

**Comment by n-a-t-e** [comment]
@fostermh this latest commit uses a few of your changes from #58. Note the different style of listing contact roles

**Comment by fostermh** [comment]
nice 👍

**Comment by n-a-t-e** [comment]
I would like to propose another change to how we are structuring the yaml. It simplifies validation and I think is more clear generally. 

Example:

Current way:
```
history_en: history in english
history_fr: history in french
```
New way:
```
history:
    en: history in english
    fr: history in french
```
Or if the value just exists in the primary language

```
history: history in english
```

I built an online validation tool the validates our yaml using these proposed changes - 

https://cioos-siooc.github.io/cioos-yaml-metadata-validate/

**Review by sjbruce — APPROVED** [review]
Works well, after rejigging the YAML input file to conform to the new conventions the generated XML is valid and accepted by CKAN.

Fields like comment, maintenance_note, limitations, acknowledgement and the are mapped as bilingual in the template - we should update the sample file after the merge to display that.

A commented out example at the top of the file for how to handle single language and bilingual fields might also be helpful.

**Pull request merged**
