### PR TITLE
add tests to ensure XML created is valid via XSD schema validation

### PR DESCRIPTION
**Pull request by n-a-t-e**
I added the files used in XSD validation, so that when we change the schema we can make sure it still creates valid XML from each of our sample records. 

Also added a Dockerfile so that these tests can be run with docker, which ensures that the tests work regardless of your local environment/uncommitted changes, also will make it easier to feed into online CI tools.

If you try running it you can see it catch an error in the master branch - `useLimitation` missing `xsi:type` attribute.

See updated README for how to run tests

### CODE REVIEW

**Review by fostermh — APPROVED** [review]
This is great, I created a branch that setup some circleCI testing and uses this. works really nicely

**Comment by jeffcullis** [comment]
Thanks Nate, I agree it great to see XML validation happening right within that repo. 

I was wondering though about including all the .xsd files in this commit. Ted Habermann who I believe is part of the ISO 19115 standards committee as well as ESIP has a GitHub repo that already contains all these files:
https://github.com/ISO-TC211/XML
It looks like this repo has a full mirror of what's on standards.iso.org. It might be preferable to pull in this repo in as a submodule rather than having our own copy of the files? Or maybe forking that repo instead?

**Comment by fostermh** [comment]
I like the submodule idea my self. I think we are currently using the stock xsd's. As we move forward with creating a validator it may be needed to modify the xsd's to capture the CIOOS profile. It's also possible this will be better done in schematron, still unclear.

UPDATE
just looked into this a bit and we are not using stock xsd's. @jeffcullis the repo you linked to does have all the root xsd's needed but some of the linked schema locations are external links. As such when running validation it first has to download these external files which makes a simple validation which should run in seconds take closer to minutes. I believe Nate downloaded and updated these external paths in the version he is using here. May still be a good idea to go the submodule root so that the same xsd's can easily be included in other cioos projects however.

**Comment by n-a-t-e** [comment]
Happy New year! I also don't love the idea of committing these files here.

One problem is, in addition the the .xsd files in the ISO-TC211 repo, there are files imported from:
http://standards.iso.org/ittf/PubliclyAvailableStandards
http://www.opengis.net/gml/3.2
http://www.w3.org/1999/

Also I used a script to change the URI imports to local imports, which alternatively could have been done with an XML Catalogue file. Eg from (https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/iso/19115/-3/gmw/1.0/gmlWrapperTypes2014.xsd):

`<xs:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19136_Schemas/gml.xsd"/>`

changed to:

`<xs:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="../../../../../ittf/PubliclyAvailableStandards/ISO_19136_Schemas/gml.xsd"/>`

Another option I was considering is CircleCI & Docker could download and extract a zip file from external URL containing these .xsd files as it's running the tests, tests would take a little bit longer to run but I think that's fine, I will show a branch that does this

**Comment by n-a-t-e** [comment]
See #30 for an alternate approach - it downloads a zip with the schema when it runs so we don't have to commit all those .xsd files

**Comment by jeffcullis** [comment]
I see, that makes sense that the external gml etc. xsd's would be a problem. Nate, your downloading approach I think makes sense as a fix for this.

Related to this, the metadata task team currently has 'Flush out the gml namespace column from ISO 19115-3 to help with xml implementations' as one of the priorities for the next version of the CIOOS profile. But that still would leave us with the ITTF and w3/1999 dependencies.

Would there be any advantage to including the standards.iso repo as a submodule and then downloading the GML/ITTF/1999 xsd's separately? I'm guessing the added complexity might not be worthwhile?

**Comment by n-a-t-e** [comment]
I think that a mix of subrepo and downloaded XSDs would work too but it would be more complicated than it's worth. I also tried using an XML Catalogue file with `xmllint` so it can use the stock XSD files downloaded from a zip and resolve the URIs locally, this worked but also a bit more complicated than needed, I think the PR #30 solution is best for now

**Comment by n-a-t-e** [comment]
Replaced by #30

**Pull request closed without merging**
