### PR TITLE
add topic_category - defaults to "oceans"

### LINKED ISSUE #82: Allow setting of TopicCategoryCode to something other then oceans
Currently `TopicCategoryCode` is hard-coded to `oceans`. Any chance we could get a parameter in there instead so we can override the hard-coded value? It could still default to `oceans` if needed. 

https://github.com/cioos-siooc/metadata-xml/blob/faea417830c2b626704f755e64479a5a72d43726/metadata_xml/iso19115-cioos-template/main.j2#L270

### PR DESCRIPTION
**Pull request by n-a-t-e**
Adds `topic_category` which defaults to "oceans". It can be one of:
```'farming', 'biota', 'boundaries', 'climatologyMeteorologyAtmosphere', 'economy', 'elevation', 'environment', 'geoscientificInformation', 'health', 'imageryBaseMapsEarthCover', 'intelligenceMilitary', 'inlandWaters', 'location', 'oceans', 'planningCadastre', 'society', 'structure', 'transportation', 'utilitiesCommunication', 'extraTerrestrial', 'disaster'```

Fixes #82

### CODE REVIEW

**Review by fostermh — DISMISSED** [review]
perfect, thanks!

**Review by fostermh — COMMENTED** [review]
one small detail, mri:topicCategory should be repeatable. ie topic_category could be a list.

**Comment by n-a-t-e** [comment]
OK, I changed it to allow for multiple topic categories

**Review by fostermh — APPROVED** [review]
so good. thanks!

**Pull request merged**
